### ISSUE TITLE
Don't overwrite the mirrolist until the sorting process is finished

### ISSUE THREAD

**Issue by cafehaine** [EgidioCaprino/rankmirrors-systemd#2]
This would allow upgrading the system before the mirrorlist is updated at startup.

**Comment by EgidioCaprino** [comment]
Hi @cafehaine

Do you mean sorting to a temporary file first? Can you please give a look at [this PR](https://github.com/EgidioCaprino/rankmirrors-systemd/pull/3/files)?

**Comment by cafehaine** [comment]
yup, that's what I meant, this PR is perfect to me!

**Comment by EgidioCaprino** [comment]
@cafehaine thank you for confirming it, AUR package updated.
